-- DROP DATABASE ARTGALLERY;
CREATE DATABASE ARTGALLERY;
USE ARTGALLERY;
-- SHOW TABLES;


#-------------------------NATIONALITY----------------------
DROP TABLE IF EXISTS NATIONALITY;
CREATE TABLE NATIONALITY (NATIONALITY_ID INT(100) NOT NULL AUTO_INCREMENT, NATIONALITY VARCHAR(50) NOT NULL UNIQUE, PRIMARY KEY(NATIONALITY_ID));
DESC NATIONALITY;


#------------Users----------
DROP TABLE IF EXISTS USERS; 
CREATE TABLE USERS(USER_ID INT(225) NOT NULL AUTO_INCREMENT, FNAME VARCHAR(20) NOT NULL ,
LNAME VARCHAR(20) NOT NULL, NATIONALITY_ID INT NOT NULL, DOB DATE NOT NULL, REG_PHNO VARCHAR(10) NOT NULL UNIQUE,  
REG_EMAIL_ID VARCHAR(100) NOT NULL UNIQUE, GENDER VARCHAR(1) NOT NULL, CURRENT_ADDRESS VARCHAR(100) NOT NULL, 
PERMANENT_ADDRESS VARCHAR(100) NOT NULL, USER_ENTITY ENUM('STAFF','CUSTOMER','ARTIST') NOT NULL, PRIMARY KEY(USER_ID), 
FOREIGN KEY(NATIONALITY_ID) REFERENCES NATIONALITY(NATIONALITY_ID));
DESC USERS;

#------LOGIN------
DROP TABLE IF EXISTS LOGIN; 
CREATE TABLE LOGIN(LOGIN_ID INT(225) NOT NULL ,PASSWORD_HASH VARCHAR(100) NOT NULL, 
PASSWORD_SALT VARCHAR(200) NOT NULL, FOREIGN KEY(LOGIN_ID) REFERENCES USERS(USER_ID));
DESC LOGIN;

#----------------PAINTING_TYPE-----------------
DROP TABLE IF EXISTS PAINTING_TYPE; 
CREATE TABLE PAINTING_TYPE (PAINTING_TYPE_ID INT(225) NOT NULL AUTO_INCREMENT, PAINTING_TYPE_NAME VARCHAR(30) NOT NULL, 
PRIMARY KEY(PAINTING_TYPE_ID));
DESC PAINTING_TYPE;

#---------------------PAITNING-------------------
DROP TABLE IF EXISTS PAINTING; 
CREATE TABLE PAINTING (PAINTING_ID INT(225) NOT NULL AUTO_INCREMENT, PAINTING_TITLE VARCHAR(30) NOT NULL, PAINTING_DATE DATE NOT NULL,
PAINTING_TYPE_ID INT NOT NULL, USER_ID INT(225) NOT NULL, PAINTING_PURCHASE_FLG INT(1) NOT NULL, PAINTING_PRICE_EURO DECIMAL(14,2) NOT NULL,
PRIMARY KEY(PAINTING_ID), FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE, FOREIGN KEY(PAINTING_TYPE_ID) REFERENCES
PAINTING_TYPE(PAINTING_TYPE_ID));

DESC PAINTING;

#---------------------EXHIBTION--------------------------
DROP TABLE IF EXISTS EXHIBITION;
CREATE TABLE EXHIBITION (EXHIBITION_ID INT(225) NOT NULL AUTO_INCREMENT , EXHIBITION_TITLE VARCHAR(20) NOT NULL, 
ESTART_DATE DATE NOT NULL, EEND_DATE DATE NOT NULL, PAINTING_ID INT(225) NOT NULL, PRIMARY KEY(EXHIBITION_ID), FOREIGN KEY(PAINTING_ID)
REFERENCES PAINTING(PAINTING_ID) ON DELETE CASCADE);

DESC EXHIBITION;

#----------------------------------PURCHASE----------------------
DROP TABLE IF EXISTS PURCHASE;
CREATE TABLE PURCHASE (PURCHASE_ID INT(225) NOT NULL AUTO_INCREMENT, PAINTING_TYPE_ID INT(225) NOT NULL, USER_ID INT(225) NOT NULL,
EXHIBITION_ID INT(225) NULL, PAINTING_ID INT(225) NOT NULL, PRIMARY KEY(PURCHASE_ID), FOREIGN KEY(PAINTING_TYPE_ID) REFERENCES PAINTING_TYPE(PAINTING_TYPE_ID),
FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE, FOREIGN KEY(PAINTING_ID) REFERENCES PAINTING(PAINTING_ID) ON DELETE CASCADE,
FOREIGN KEY(EXHIBITION_ID) REFERENCES EXHIBITION(EXHIBITION_ID));

DESC PURCHASE;

#-------------------PEN_NAME---------
DROP TABLE IF EXISTS PEN_NAME; 
CREATE TABLE PEN_NAME (USER_ID INT(225) NOT NULL,PEN_NAME VARCHAR(40) NOT NULL, FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)); 
DESC PEN_NAME;

#---------------------------STORED PROCEDURES---------------------
DELIMITER $$
USE `artgallery`$$
CREATE PROCEDURE `PURCHASE_FLG` (IN P_ID INT)
BEGIN
UPDATE PAINTING 
SET PAINTING_PURCHASE_FLG=1 WHERE PAINTING_ID=P_ID; 
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MOST_SOLD_PAINTINGS`()
BEGIN
SELECT PAINTING_TYPE_NAME, COUNT(PAINTING_ID) FROM (SELECT DISTINCT A.PAINTING_TYPE_NAME, B.PAINTING_ID FROM PAINTING_TYPE A 
LEFT JOIN PAINTING B ON A.PAINTING_TYPE_ID=B.PAINTING_TYPE_ID) VALS GROUP BY PAINTING_TYPE_NAME ORDER BY 2 DESC;
END$$
DELIMITER ;


USE `artgallery`;
DROP procedure IF EXISTS `FAV_ARTIST`;

DELIMITER $$
USE `artgallery`$$
CREATE PROCEDURE `FAV_ARTIST` ()
BEGIN
SELECT USER_FNAME, COUNT(PAINTING_ID) FROM (SELECT DISTINCT A.PAINTING_TYPE_NAME, B.PAINTING_ID FROM PAINTING_TYPE A 
LEFT JOIN PAINTING B ON A.PAINTING_TYPE_ID=B.PAINTING_TYPE_ID WHERE B.PAINTING_PURCHASE_FLG=1) VALS GROUP BY PAINTING_TYPE_NAME ORDER BY 2 DESC;
END$$

DELIMITER ;

DELIMITER $$
USE `artgallery`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ARTIST_DETAILS`(UID INT)
BEGIN
SELECT USR.FNAME AS 'FIRST NAME',USR.LNAME AS 'LAST NAME' ,PAINT.PAINTING_TITLE,PAINT.PAINTING_PURCHASE_FLG AS 'PURCHASE FLAG', PAINT.PAINTING_DATE FROM USERS USR LEFT JOIN PAINTING PAINT ON USR.USER_ID=PAINT.USER_ID WHERE USR.USER_ID=UID;
END$$

DELIMITER ;